all: undirectedGraphtest

undirectedGraphtest: undirectedGraphtest.cpp undirectedGraph.cpp undirectedGraph.h
	g++ -std=c++11 -o  undirectedGraphtest undirectedGraphtest.cpp undirectedGraph.cpp

# List all the executables under 'all:'
clean:
	rm undirectedGraphtest