# List all the drivers
all: playlisttest
 


playlisttest: playlisttest.cpp Playlist.h
	g++ -std=c++11 -o  playlisttest playlisttest.cpp



# List all the executables under 'all:'
clean:
	rm playlisttest