all: quadtreetest

quadtreetest: quadtreetest.cpp quadtree.cpp quadtree.h
	g++ -std=c++11 -o  quadtreetest quadtreetest.cpp quadtree.cpp

# List all the executables under 'all:'
clean:
	rm quadtreetest